### ISSUE TITLE
hub.docke.com 貌似构建失败了

### ISSUE THREAD

**Issue by kongminhao** [Thoxvi/Dont-Starve-Together-Docker-Cluster#2]
由于网络原因，要不要重新构建一波？

![](http://ofqm89vhw.bkt.clouddn.com/ab86388b51afde76edd155bc45081247.png)

**Comment by kongminhao** [comment]
https://hub.docker.com/r/thoxvi/dont-starve-together-docker-cluster/builds/bnktvd7tawbbwmhbfcxvpjd/

**Comment by Thoxvi** [comment]
。。。
我去试试。。。

**Comment by Thoxvi** [comment]
换回了官方源，构建成功了 ; )
